// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 持久化应用配置到 system.db 的 system_config 表。
 * 采用 key-value 设计：Config 结构体的每个字段对应一条记录，value 为
 * JSON 编码后的值，可统一存储 string / int / bool / []string。
 * 新增配置项只需插入新 key，无需改表结构（可拓展）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AddRecentFile 将 path 加入近期文件列表（去重、上限 10）。
 */
export function AddRecentFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(3154178366, path);
}

/**
 * AddRecentFolder 将 path 加入近期文件夹列表（去重、上限 10）。
 */
export function AddRecentFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2882864300, path);
}

/**
 * ClearRecentFolders 清空近期文件夹列表。
 */
export function ClearRecentFolders(): $CancellablePromise<void> {
    return $Call.ByID(4108065111);
}

/**
 * GetBool 读取布尔配置；不存在返回 false。
 */
export function GetBool(key: string): $CancellablePromise<boolean> {
    return $Call.ByID(4141574508, key);
}

/**
 * GetConfig 从 system_config 表读取全部配置，缺失字段用默认值兜底。
 */
export function GetConfig(): $CancellablePromise<model$0.Config> {
    return $Call.ByID(2304121202);
}

/**
 * GetInt 读取整数配置；不存在返回 0。
 */
export function GetInt(key: string): $CancellablePromise<number> {
    return $Call.ByID(1306620365, key);
}

/**
 * GetString 读取字符串配置；不存在返回空字符串。
 */
export function GetString(key: string): $CancellablePromise<string> {
    return $Call.ByID(587083413, key);
}

/**
 * GetStrings 读取字符串切片配置；不存在返回 nil。
 */
export function GetStrings(key: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(4230206482, key);
}

/**
 * MigrateFromLegacyJSON 若旧版 config.json 存在且 system_config 尚无记录，
 * 把它的字段逐条导入 system_config，然后删除旧文件。幂等：表中已有记录则跳过。
 */
export function MigrateFromLegacyJSON(): $CancellablePromise<void> {
    return $Call.ByID(1257567704);
}

/**
 * PathExists 判断路径在文件系统中是否存在。
 */
export function PathExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(300478815, path);
}

/**
 * RemoveRecentFolder 从近期文件夹列表移除 path。
 */
export function RemoveRecentFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(293468255, path);
}

/**
 * SetBool 写入布尔配置。
 */
export function SetBool(key: string, value: boolean): $CancellablePromise<void> {
    return $Call.ByID(216717048, key, value);
}

/**
 * SetConfig 把整个 Config 写入 system_config 表（逐条 upsert）。
 */
export function SetConfig(cfg: model$0.Config): $CancellablePromise<void> {
    return $Call.ByID(2182891558, cfg);
}

/**
 * SetInt 写入整数配置。
 */
export function SetInt(key: string, value: number): $CancellablePromise<void> {
    return $Call.ByID(3257279113, key, value);
}

/**
 * SetString 写入字符串配置。
 */
export function SetString(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2996595985, key, value);
}

/**
 * SetStrings 写入字符串切片配置。
 */
export function SetStrings(key: string, value: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2386571590, key, value);
}
