// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService renders markdown to HTML / DOCX / TXT by shelling out to a
 * local pandoc binary. PDF export (ExportPDFFromHTML) does not use pandoc:
 * the frontend renders the document with Vditor.preview and Microsoft Edge
 * headless prints it to PDF, matching the window.print() output exactly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckPandoc returns the pandoc availability and version string.
 */
export function CheckPandoc(): $CancellablePromise<$models.PandocInfo> {
    return $Call.ByID(1054160495);
}

/**
 * CheckPandocPath validates a specific pandoc executable chosen by the user:
 * it runs `pandoc --version` on it and reports availability/version.
 */
export function CheckPandocPath(path: string): $CancellablePromise<$models.PandocInfo> {
    return $Call.ByID(1974620360, path);
}

/**
 * ExportDOCX converts markdown to a Word document at outPath. Requires only pandoc.
 */
export function ExportDOCX(markdown: string, workDir: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(1884297780, markdown, workDir, outPath);
}

/**
 * ExportFile converts an already-saved markdown file by path.
 * format is "html", "docx", "txt" or "md". The document is passed to pandoc
 * as an input file with its own directory as working directory, so large
 * documents and their image resources never cross the frontend<->Go bridge as
 * strings. PDF is not supported here: it goes through ExportPDFFromHTML
 * (Microsoft Edge headless) instead.
 */
export function ExportFile(mdPath: string, outPath: string, format: string): $CancellablePromise<void> {
    return $Call.ByID(2862400860, mdPath, outPath, format);
}

/**
 * ExportHTML converts markdown to a standalone HTML document written to
 * outPath. Images are resolved relative to workDir (usually the document
 * directory).
 */
export function ExportHTML(markdown: string, workDir: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(583820391, markdown, workDir, outPath);
}

/**
 * ExportMD writes markdown to outPath with every local image embedded as a
 * base64 data URL, producing a single self-contained .md file. Remote URLs
 * and existing data URLs are kept unchanged; unreadable local files keep
 * their original reference (graceful degradation).
 */
export function ExportMD(markdown: string, workDir: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(3601599811, markdown, workDir, outPath);
}

/**
 * ExportPDFFromHTML 用 Microsoft Edge headless 把已渲染好的 HTML 渲染为 PDF。
 * 与前端 window.print() 路径共享同一份 HTML 渲染产物（Vditor.preview 输出 +
 * resolveImagesIn 把图片转 data URL），因此公式（KaTeX）、代码高亮、表格样式与
 * 打印效果完全一致。
 * 
 * 步骤：
 *  1. 创建临时目录，把嵌入的 vditor 静态资源（CSS、KaTeX 字体）解压到 tmpdir/vditor/
 *  2. 写 tmpdir/print.html：<link href="vditor/dist/index.css"> + 打印 CSS + 前端传入的 body
 *  3. msedge --headless=new --no-pdf-header-footer --print-to-pdf=<outPath> file:///tmpdir/print.html
 * 
 * msedge 渲染引擎与 WebView2 同源，公式（KaTeX）/代码高亮/表格完美渲染。
 */
export function ExportPDFFromHTML(htmlBody: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(3415517309, htmlBody, outPath);
}

/**
 * ExportTXT converts markdown to plain text at outPath. Pandoc's "plain"
 * writer renders headings/bold/lists as readable text, not raw markdown.
 */
export function ExportTXT(markdown: string, workDir: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(1930887174, markdown, workDir, outPath);
}
