// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService handles all local filesystem operations for the frontend.
 * Frontend code must never touch the filesystem directly; it always goes
 * through this service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyFile copies a file into destDirPath. Name collisions are resolved by
 * appending " (n)" before the extension (e.g. "a (1).md"). Returns the final
 * destination path. Directories are not supported.
 */
export function CopyFile(srcPath: string, destDirPath: string): $CancellablePromise<string> {
    return $Call.ByID(3280562887, srcPath, destDirPath);
}

/**
 * CreateDirectory creates a new directory at path, including any necessary
 * parents. It is a no-op (returns nil) if the directory already exists.
 */
export function CreateDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(1068995307, path);
}

/**
 * DeleteFile removes a file or directory at path. Directories are removed
 * recursively.
 */
export function DeleteFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(3988020873, path);
}

/**
 * GetFileInfo returns detailed file metadata for the properties dialog. The
 * ReadOnly flag is derived from the owner write bit (perm & 0200 == 0).
 */
export function GetFileInfo(path: string): $CancellablePromise<$models.FileInfo> {
    return $Call.ByID(2519426910, path);
}

/**
 * IsDirectory reports whether path is a directory.
 */
export function IsDirectory(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(4177304159, path);
}

/**
 * JoinPath joins path elements using the platform separator and returns the
 * result. This lets the frontend build child paths without knowing the OS.
 */
export function JoinPath(...elem: string[]): $CancellablePromise<string> {
    return $Call.ByID(3014388347, elem);
}

/**
 * MovePath moves the file or directory at srcPath into the directory
 * destDirPath, preserving its base name, and returns the new absolute path.
 * It rejects: moving into itself, moving a directory into one of its own
 * descendants, a missing destination directory and name collisions in the
 * target folder (resolved by appending " (n)", same as CopyFile).
 */
export function MovePath(srcPath: string, destDirPath: string): $CancellablePromise<string> {
    return $Call.ByID(779524850, srcPath, destDirPath);
}

/**
 * PathExists reports whether path exists on the filesystem.
 */
export function PathExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1003990507, path);
}

/**
 * PickOpenDirectory shows the native directory-picker dialog and returns the
 * chosen directory path, or an empty string if the user cancels.
 */
export function PickOpenDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3297384500);
}

/**
 * PickOpenFile shows the native open-file dialog and returns the chosen path,
 * or an empty string if the user cancels.
 */
export function PickOpenFile(): $CancellablePromise<string> {
    return $Call.ByID(2520353055);
}

/**
 * PickPandocFile shows the native open-file dialog defaulting to executable
 * files, used for picking a pandoc binary in the settings dialog.
 */
export function PickPandocFile(): $CancellablePromise<string> {
    return $Call.ByID(632010516);
}

/**
 * PickSaveFile shows the native save-file dialog seeded with defaultName and
 * returns the chosen path, or an empty string if the user cancels.
 */
export function PickSaveFile(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(3099228878, defaultName);
}

/**
 * ReadDirectory lists the immediate children of dir. Each entry contains
 * name, absolute path, isDir flag, size and modTime.
 */
export function ReadDirectory(dir: string): $CancellablePromise<$models.DirEntry[] | null> {
    return $Call.ByID(958075667, dir);
}

/**
 * ReadFile reads the entire file at path as UTF-8 text and returns its content.
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1653546182, path);
}

/**
 * RenamePath renames the file or directory at oldPath to newName within the
 * same directory and returns the new absolute path. It rejects empty names,
 * names containing path separators or characters that are illegal on Windows,
 * and target names that already exist (duplicate-name check).
 */
export function RenamePath(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(1740844341, oldPath, newName);
}

/**
 * RevealInExplorer opens Windows Explorer with the given file selected. On
 * non-Windows platforms it returns an error.
 */
export function RevealInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(4065779149, path);
}

/**
 * Stat returns metadata for a file without transferring its contents,
 * letting the frontend decide whether a path-based operation is possible.
 */
export function Stat(path: string): $CancellablePromise<$models.DirEntry> {
    return $Call.ByID(1735649118, path);
}

/**
 * WriteFile writes content to path, creating the file if it does not exist
 * and truncating it if it does.
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3465247205, path, content);
}
