// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImageService persists images pasted or dropped into the editor. Images are
 * stored under an "assets" sub-directory next to the document and named after
 * the SHA-1 of their binary content (de-duplicated).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ReadFileBase64 reads a local image file and returns it as a data URL so the
 * WebView can display images referenced by relative paths in markdown (the
 * webview origin cannot fetch files from disk directly). Missing files return
 * an error which the frontend ignores, leaving the original src untouched.
 */
export function ReadFileBase64(path: string): $CancellablePromise<string> {
    return $Call.ByID(3839281416, path);
}

/**
 * SaveImage decodes a data URL ("data:image/png;base64,....") and writes the
 * binary to the configured image directory (config.imageDir, defaulting to
 * <userConfigDir>/XinText/images), named after the SHA-1 of its content
 * (de-duplicated). It returns the absolute path with forward slashes so the
 * markdown reference works across editors and pandoc exports:
 * e.g. "D:/XinText/images/abc.png".
 */
export function SaveImage(dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(986185497, dataURL);
}
