// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService 把 Go 后端 stdout 日志和前端 console 日志分别写入
 * `go.log` 与 `frontend.log` 两个文件，供日志浮层查看与清理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ClearFrontendLog 清空 frontend.log。
 */
export function ClearFrontendLog(): $CancellablePromise<void> {
    return $Call.ByID(3435607083);
}

/**
 * ClearGoLog 清空 go.log。
 */
export function ClearGoLog(): $CancellablePromise<void> {
    return $Call.ByID(321657129);
}

/**
 * Close 关闭文件句柄，main 退出时 defer 调用。
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(452980610);
}

/**
 * GetDefaultLogDir 返回默认日志目录路径，供前端显示提示。
 */
export function GetDefaultLogDir(): $CancellablePromise<string> {
    return $Call.ByID(3609256862);
}

/**
 * GetLogDir 返回当前日志目录绝对路径。
 */
export function GetLogDir(): $CancellablePromise<string> {
    return $Call.ByID(30924287);
}

/**
 * GoPrintf 显式写入 go.log，不依赖全局 log.SetOutput，也不写 os.Stdout。
 * 必须用 goLogger（只写 goFile）而非 stdLogger（MultiWriter 含 os.Stdout）：
 * wails3 build 的 -H windowsgui 标志使 os.Stdout 变为无效句柄，
 * io.MultiWriter 写 stdout 失败后会跳过 goFile，导致日志丢失。
 * 如需 dev 模式 stdout 输出，请单独调用 log.Printf。
 */
export function GoPrintf(format: string, ...args: any[]): $CancellablePromise<void> {
    return $Call.ByID(753876799, format, args);
}

/**
 * InitStdLogger 把标准 log 的输出重定向为「go.log + stdout」。
 * goFile 必须放在 MultiWriter 第一位：wails3 build 的 -H windowsgui 标志
 * 使 os.Stdout 变为无效句柄，io.MultiWriter 写 stdout 失败后会跳过后续 writer，
 * 把 goFile 放前面可确保日志先写入文件，stdout 失败不影响文件写入。
 * 注意：Wails 在 application.New() 内部可能再次覆盖标准 log 的输出，
 * 因此关键启动日志应使用 GoPrintf 显式写入，不依赖此全局重定向。
 */
export function InitStdLogger(): $CancellablePromise<void> {
    return $Call.ByID(3898369837);
}

/**
 * ReadFrontendLog 读取 frontend.log 全文返回。
 */
export function ReadFrontendLog(): $CancellablePromise<string> {
    return $Call.ByID(498843364);
}

/**
 * ReadGoLog 读取 go.log 全文返回。
 */
export function ReadGoLog(): $CancellablePromise<string> {
    return $Call.ByID(3582558078);
}

/**
 * SetLogDir 切换日志目录：关闭旧文件 → 创建新目录 → 打开新文件。
 * 空字符串回退到默认目录。返回新的日志目录绝对路径。
 */
export function SetLogDir(newDir: string): $CancellablePromise<string> {
    return $Call.ByID(3271728747, newDir);
}

/**
 * WriteFrontend 由前端调用，把 console 日志写入 frontend.log。
 * level 形如 "log"/"info"/"warn"/"error"。
 */
export function WriteFrontend(level: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(4167205745, level, msg);
}
