// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirEntry is a simplified directory entry returned by ReadDirectory.
 */
export interface DirEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * unix seconds
     */
    "modTime": number;
}

/**
 * FileInfo carries detailed metadata for a single file, used by the frontend's
 * properties dialog.
 */
export interface FileInfo {
    "name": string;
    "path": string;

    /**
     * bytes
     */
    "size": number;
    "isDir": boolean;

    /**
     * unix seconds (last modified)
     */
    "modTime": number;

    /**
     * unix seconds (creation time, 0 if unavailable)
     */
    "createTime": number;

    /**
     * file mode bits
     */
    "mode": number;
    "readOnly": boolean;
}

/**
 * PandocInfo reports whether pandoc is available and its version string.
 */
export interface PandocInfo {
    "available": boolean;
    "path": string;
    "version": string;
}

/**
 * RecycleItem 是 file_recycle 表的一条记录，对应回收站内的一个文件或目录。
 */
export interface RecycleItem {
    "id": number;

    /**
     * 文件/目录名
     */
    "name": string;

    /**
     * 删除前的绝对路径
     */
    "originalPath": string;

    /**
     * 回收站中的实际存储路径
     */
    "recyclePath": string;

    /**
     * 项目类型：true=目录 false=文件
     */
    "isDir": boolean;

    /**
     * 字节；目录为递归总大小
     */
    "size": number;

    /**
     * 删除时间（unix 秒）
     */
    "deletedAt": number;
}

/**
 * SearchHit 表示一条全文检索命中（文件中的一行）。
 */
export interface SearchHit {
    /**
     * 文件绝对路径
     */
    "path": string;

    /**
     * 文件名
     */
    "name": string;

    /**
     * 行号（从 1 开始）
     */
    "lineNumber": number;

    /**
     * 命中行去空白后的片段
     */
    "snippet": string;

    /**
     * 片段内全部命中位置（多关键词、多次出现）
     */
    "matches": TextMatch[] | null;
}

/**
 * TextMatch 描述一条命中中单个关键词的位置区间（rune 下标，左闭右开），
 * 坐标相对于 SearchHit.Snippet。
 */
export interface TextMatch {
    /**
     * 起始 rune 下标（含）
     */
    "start": number;

    /**
     * 结束 rune 下标（不含）
     */
    "end": number;
}

/**
 * UpdateInfo 版本更新检测结果，返回前端
 */
export interface UpdateInfo {
    /**
     * 当前版本
     */
    "currentVersion": string;

    /**
     * 远端最新版本（tag_name，已去掉前导 v）
     */
    "latestVersion": string;

    /**
     * 是否存在新版本
     */
    "hasUpdate": boolean;

    /**
     * 是否为预发布版本
     */
    "prerelease": boolean;

    /**
     * 发布标题
     */
    "releaseName": string;

    /**
     * 更新说明（body 原文）
     */
    "releaseNotes": string;

    /**
     * 发布时间（yyyy-MM-dd）
     */
    "publishedAt": string;

    /**
     * 发布页面地址
     */
    "releaseUrl": string;

    /**
     * 优先 .exe 附件的下载地址
     */
    "downloadUrl": string;

    /**
     * ok 或错误提示
     */
    "msg": string;
}
