// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecycleService 实现应用内回收站：删除的文件/目录移动到回收站目录，
 * 元数据记录在 system.db 的 file_recycle 表中，支持还原 / 还原到 /
 * 彻底删除 / 清空。回收站目录可由用户在设置中自定义。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close 释放数据库连接（仅当服务持有时；共享连接由调用方管理）。
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(4019665563);
}

/**
 * DeleteRecycleItemPermanent 彻底删除单个项目并清除记录。
 */
export function DeleteRecycleItemPermanent(id: number): $CancellablePromise<void> {
    return $Call.ByID(1992381958, id);
}

/**
 * EmptyRecycle 彻底删除回收站中的全部项目并清空记录表。
 * 单项物理删除失败时保留其记录并返回错误，其余项目继续清理。
 */
export function EmptyRecycle(): $CancellablePromise<void> {
    return $Call.ByID(2674503571);
}

/**
 * GetRecycleDir 返回当前生效的回收站目录。
 */
export function GetRecycleDir(): $CancellablePromise<string> {
    return $Call.ByID(368255615);
}

/**
 * ListRecycleItems 返回回收站全部记录，按删除时间倒序。
 */
export function ListRecycleItems(): $CancellablePromise<$models.RecycleItem[] | null> {
    return $Call.ByID(3585476398);
}

/**
 * MoveToRecycle 把 srcPath 移动到回收站目录，并写入 file_recycle 记录。
 * 跨卷（自定义目录位于其他盘）时 os.Rename 会失败，自动退回复制+删除。
 */
export function MoveToRecycle(srcPath: string): $CancellablePromise<void> {
    return $Call.ByID(2019733598, srcPath);
}

/**
 * RestoreRecycleItem 还原到原路径；原路径的父目录不存在时自动创建，
 * 同名冲突按 “名称 (n)” 追加。还原成功后删除回收站记录。
 */
export function RestoreRecycleItem(id: number): $CancellablePromise<void> {
    return $Call.ByID(1791854681, id);
}

/**
 * RestoreRecycleItemTo 还原到指定目录（目录不存在会创建），同名冲突自动追加
 * “名称 (n)”。还原成功后删除回收站记录。
 */
export function RestoreRecycleItemTo(id: number, destDirPath: string): $CancellablePromise<void> {
    return $Call.ByID(1614571976, id, destDirPath);
}

/**
 * SetRecycleDir 自定义回收站目录；空串表示恢复默认。目录不存在会自动创建，
 * 创建失败时不持久化。返回设置后生效的绝对目录。
 */
export function SetRecycleDir(dir: string): $CancellablePromise<string> {
    return $Call.ByID(3295241771, dir);
}
