// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService 在已打开目录内对文档做关键字全文检索。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SearchInDirectory 递归检索 dir 下的文档，返回命中行。
 * keyword 支持空格分隔的多个关键词，采用 AND 语义（一行包含全部关键词
 * 才算命中，大小写不敏感）。extFilter: "md"（.md/.markdown）、"txt"
 * （.txt）、其他值（含 "all"）表示同时检索 md 与 txt。
 */
export function SearchInDirectory(dir: string, keyword: string, extFilter: string): $CancellablePromise<$models.SearchHit[] | null> {
    return $Call.ByID(423531492, dir, keyword, extFilter);
}
