// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WatchService uses fsnotify to watch one or more directories for filesystem
 * changes and broadcasts them to the frontend via Wails events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Close shuts down the watcher.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(823685881);
}

/**
 * Unwatch removes a directory and all its watched subdirectories from the
 * watcher.
 */
export function Unwatch(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2228330871, dir);
}

/**
 * Watch starts watching dir and all of its subdirectories recursively. If the
 * same directory is already watched this is a no-op.
 */
export function Watch(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2152514338, dir);
}
