// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config holds persisted application preferences.
 * It is stored as JSON under the OS user config dir (e.g. %AppData%/XinText).
 */
export interface Config {
    "windowWidth": number;
    "windowHeight": number;
    "theme": string;

    /**
     * 界面语言：zh / en；空 = 跟随系统
     */
    "language": string;
    "recentFiles": string[] | null;
    "recentFolders": string[] | null;
    "projectPath": string;
    "pandocPath": string;

    /**
     * 图片统一保存目录；空 = <userConfigDir>/XinText/images
     */
    "imageDir": string;

    /**
     * 日志目录；空 = <userConfigDir>/XinText/logs
     */
    "logDir": string;

    /**
     * 回收站目录；空 = <userConfigDir>/XinText/recycle
     */
    "recycleDir": string;

    /**
     * 浏览器标签页主页 URL；空 = 内置默认（kevin.blog.csdn.net）
     */
    "browserHomeURL": string;

    /**
     * 自动保存：编辑后 10s 无操作自动写盘；nil/未设置 = 关闭（默认 false）
     */
    "autoSave"?: boolean | null;
}
